import Head from 'next/head'

import Layout from '../components/common/Layout.component'
import { Fragment } from 'react'

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>NOT GOJEK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='h-full grid place-items-center'>
        <img
          src='/this-is-cat.png'
          className='cursor-pointer'
          onClick={(e) => e.target.classList.toggle('invert')}
        ></img>
      </div>
    </Fragment>
  )
}
