import Head from 'next/head'

import Layout from '../components/common/Layout'
import { Fragment } from 'react'

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>NOT GOJEK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout
        skips={true}
        page={'NOT GOJEK'}
        description={
          'You can drive wherever you want, whenever you want, and eat anything you want without leaving your house!'
        }
      >
        <div className='flex justify-center m-16'>
          <img
            src='/cat.png'
            className='cursor-pointer'
            onClick={(e) => e.target.classList.toggle('invert')}
          ></img>
        </div>
      </Layout>
    </Fragment>
  )
}
