import { Fragment } from 'react'
import Head from 'next/head'

import { MongoClient } from 'mongodb'

import RestaurantList from '../../components/go-food/RestaurantContent.component'

function NotGoFoodApp({ restaurants }) {
  return (
    <Fragment>
      <Head>
        <title>GO-FOOD - NOT GOJEK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <RestaurantList restaurantList={restaurants} />
    </Fragment>
  )
}

export async function getStaticProps() {
  const client = await MongoClient.connect(
    `mongodb+srv://${process.env.MONGODB_USERNAME}:${process.env.MONGODB_PASSWORD}@cluster0.ec2ky.mongodb.net/${process.env.MONGODB_DATABASE}?retryWrites=true&w=majority`
  )
  const database = client.db()
  const collections = database.collection('go-food')
  const restaurants = await collections.find().toArray()
  client.close()

  const response = restaurants.map((res) => ({
    id: res._id.toString(),
    name: res.name,
    menus: res.menus.length,
  }))

  return {
    props: {
      restaurants: response,
    },
    revalidate: 1,
  }
}

export default NotGoFoodApp
