import { Fragment, useState, useEffect, useContext } from 'react'
import Head from 'next/head'

import ContextProvider, { GlobalContext } from '../../state/contextProvider'

import Layout from '../../components/common/Layout'
import CollapsibleTable from '../../components/tables/data-tables-food'

export default function OrderHistory() {
  const [goFood, setGoFood] = useContext(GlobalContext)
  const [goRide, setGoRide] = useContext(GlobalContext)
  const [openTab, setOpenTab] = useState(null)

  const styles = {
    active: 'border-[#00a770] text-[#ffffff] bg-[#00a770]',
    button:
      'cursor-pointer capitalize border border-[#d6d6d6] transition ease-in-out duration-200 hover:border-[#00a770] hover:text-[#ffffff] hover:bg-[#00a770] p-2 px-4',
  }

  useEffect(() => {
    setOpenTab(
      goFood.length > 0 ? 'go-food' : goRide.length > 0 ? 'go-ride' : null
    )
  }, [])

  return (
    <Fragment>
      <Head>
        <title>YOUR HISTORY - NOT GOJEK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout skips={{}}>
        <div className='my-8'>
          <h1 className='uppercase font-semibold text-3xl lg:text-5xl mx-5 lg:mx-10'>
            your order history
          </h1>
          <div className='flex justify-end border-b border-[#eaeaea] space-x-8 my-4 py-4 px-5 lg:px-10'>
            <div
              className={`${styles.button} ${
                openTab === 'go-food' && styles.active
              }`}
            >
              go food
            </div>
            <div
              className={`${styles.button} ${
                openTab === 'go-ride' && styles.active
              }`}
            >
              go ride
            </div>
          </div>
          <div className='mx-5 lg:mx-10'>
            <CollapsibleTable restaurants={goFood} />
          </div>
        </div>
      </Layout>
    </Fragment>
  )
}
